### ISSUE TITLE
Issue running vagrant server - Windows

### ISSUE THREAD

**Issue by wingZero21** [opscode-cookbooks/chef-server#62]
Hi,

When trying to run the vagrant server currently. I am getting the below error.

I can see quite a few other people having the same issue on these threads here.(https://github.com/opscode/chef-dk/issues/106)

Can you advise what the fix is for this as reading through these threads currently its not really clear.

I am using the latest chef-dk currently.

Cheers

Details:
Error:
```
Installing chef_handler (1.1.6)
E, [2014-11-19T13:54:42.116679 #10488] ERROR -- : Actor crashed!
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:918:in `connect'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:918:in `connect'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:851:in `start'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:1367:in `request'
        C:/opscode/chefdk/embedded/lib/ruby/2.0.0/net/http.rb:1126:in `get'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:78:in `perform_request'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/request/retry.rb:87:in `call'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.0/lib/ridley/middleware/follow_redirects.rb:67:in `perform_with_redirection'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/ridley-4.1.0/lib/ridley/middleware/follow_redirects.rb:60:in `call'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:119:in `find'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:103:in `download'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:62:in `try_download'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:36:in `block in download'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `download'
        C:/opscode/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        C:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by jtimberman** [comment]
Your system is failing to validate the SSL certificate. It's not clear to me why this is opened in the chef-server cookbook repository though. I suggest you email the Chef user mailing list with more information such as the version of the Chef Server you're using, plus how you installed it.
